# Worker target for monorepo deployment platforms.
providers = ["go"]

[phases.setup]
nixPkgs = ["go"]

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = ["go build -ldflags=\"-w -s\" -o /app/bin/worker ."]

[start]
cmd = "/app/bin/worker"
